ongr_elasticsearch:
    analysis:
        analyzer:
            keywordAnalyzer:
                type: custom
                tokenizer: keyword
                filter: [lowercase]
            incrementalAnalyzer:
                type: custom
                tokenizer: standard
                filter:
                    - lowercase
                    - asciifolding

ongr_filter_manager:
    managers:
        search_list:
            filters:
                - channel
                - enabled
                - taxonCode
                - taxonSlug
                - priceRange
                - inStock
                - locale
                - paginator
                - search
                - attributes
                - attributesByCode
                - options
                - sort
            repository: es.manager.default.product
    filters:
        channel:
            type: choice
            request_field: channel
            document_field: channel_code
        enabled:
            type: choice
            request_field: enabled
            document_field: enabled
        taxonCode:
            type: sylius_elastic_search.choice_nested
            request_field: taxonCode
            document_field: taxons>taxons.code
        taxonSlug:
            type: sylius_elastic_search.choice_nested
            request_field: taxonSlug
            document_field: taxons>taxons.slug
        priceRange:
            type: range
            request_field: price
            document_field: price.amount
            options:
                inclusive: true
        inStock:
            type: sylius_elastic_search.in_stock
            request_field: stock
            document_field: variants.stock
            options:
                inclusive: true
        locale:
            type: choice
            request_field: locale
            document_field: locale_code
        paginator:
            type: sylius_elastic_search.custom_pager
            document_field: ~
            request_field: page
            options:
                limit: 9
                max_pages: 20
        attributes:
            type: sylius_elastic_search.multi_dynamic_aggregate
            request_field: attributes
            document_field: attributes>attributes.value.raw
            options:
                name_field: attributes.name.raw
                names_sort_type: _term
                names_sort_order: asc
                names_size: 100
                values_sort_type: _count
                values_sort_order: desc
                values_size: 100
        attributesByCode:
            type: sylius_elastic_search.multi_dynamic_aggregate_without_view
            request_field: attributesByCode
            document_field: attributes>attributes.value.raw
            options:
                name_field: attributes.code
        options:
            type: sylius_elastic_search.multi_dynamic_aggregate_options
            request_field: options
            document_field: variants>variants.options>variants.options.value.raw
            options:
                name_field: variants.options.name.raw
                sort_type: _term
                sort_order: asc
                size: 100
        search:
            type: match
            request_field: search
            document_field: id,name^3,description,attributes>attributes.name.standard,attributes>attributes.value.standard
            options:
                operator: and
        sort:
            type: sylius_elastic_search.sort
            request_field: sort
            document_field: ~
            options:
                aliases:
                    name: name
                    slug: slug
                    code: code
                    price: price.amount
                    date: created_at
